version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: zrp-rickmorty-redis-local
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no"]
    restart: unless-stopped


